export const offerData = [
    {
        id:`1`,
        classname:`Scalable offer-item`,
        heading:`Scalable`,
        des:`Our consensus mechanisms — Lachesis and TxFlow — can scale where others cannot.`,
        img:`/images/offer-icon/scalable.svg`,
        alt:`Scalable`,
    },
    {
        id:`2`,
        classname:`Secure offer-item`,
        heading:`Secure`,
        des:`Asynchronous Byzantine Fault Tolerant consensus mechanisms provide bank-grade security for any distributed ledger application.`,
        img:`/images/offer-icon/secure.svg`,
        alt:`Secure`,
    },
    {
        id:`3`,
        classname:`Fast offer-item`,
        heading:`Fast`,
        des:`Fantom consensus is designed to support high throughput, while maintaining security, responsivity, and quick settlements.`,
        img:`/images/offer-icon/fast.svg`,
        alt:`Fast`,
    },
    {
        id:`4`,
        classname:`Connected offer-item`,
        heading:`Connected`,
        des:`Products and blockchains using Fantom SDK can interact with each other through non-custodial bridges and bonded tokens.`,
        img:`/images/offer-icon/Connected.svg`,
        alt:`Connected`,
    },
    {
        id:`5`,
        classname:`Permissionless offer-item`,
        heading:`Permissionless`,
        des:`We designed Fantom SDK to be used with networks that are secured through Proof-of-Stake, with on-chain governance for maximum network participation.`,
        img:`/images/offer-icon/Permissionless.svg`,
        alt:`Permissionless`,
    },
    {
        id:`6`,
        classname:`Open-source offer-item`,
        heading:`Open-source`,
        des:`All code, research, and repositories created by the Fantom core development team are available publicly for peer review and improvements.`,
        img:`/images/offer-icon/openSource.svg`,
        alt:`Open-source`,
    },
]