export const teamMemberData = [
    {
        id : 1,
        imgUrl : `/images/team-member/Michael Kong.png`,
        imgAlt : `Michael Kong`,
        name : `Michael Kong`,
        designation : `CIO`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Michael kong`,
        linkedInUrl : `https://www.linkedin.com/in/michael-kong-89817544/`,
    },
    {
        id : 2,
        imgUrl : `/images/team-member/xMichael.png.pagespeed.ic.myh9n1dicT.png`,
        imgAlt : `Michael Chen`,
        name : `Michael Chen`,
        designation : `CMO`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Michael`,
        linkedInUrl : `https://www.linkedin.com/in/michael-chen-b982a9157/`,
    },
    {
        id :  3,
        imgUrl : `/images/team-member/simons.gif`,
        imgAlt : `Simone Pomposi`,
        name : `Simone Pomposi`,
        designation : `Marketing & Design`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Simone Pomposi`,
        linkedInUrl : `https://www.linkedin.com/in/simonepomposi/`,
    },
    // {
    //     id : 3,
    //     imgUrl : `/images/team-member/Guillaume Drevon.png`,
    //     imgAlt : `Guillaume Drevon`,
    //     name : `Guillaume Drevon`,
    //     designation : `Cryptography`,
    //     linkedInImg : `/images/team-member/linkedin.png`,
    //     linkedInAlt : `linkedin Guillaume`,
    //     linkedInUrl : `https://www.linkedin.com/in/bariq-sikandari-597752153/`,
    // },
    {
        id : 4,
        imgUrl : `/images/team-member/Barek Sekandari.png`,
        imgAlt : `Barek Sekandari`,
        name : `Barek Sekandari`,
        designation : `Partnerships`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Barek`,
        linkedInUrl : `https://www.linkedin.com/in/bariq-sikandari-597752153/`,
    },
    {
        id : 5,
        imgUrl : `/images/team-member/Samuel-Harcourt.png`,
        imgAlt : `Samuel Harcourt`,
        name : `Samuel Harcourt`,
        designation : `Partnerships`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Harcourt`,
        linkedInUrl : `https://www.linkedin.com/in/samuel-harcourt-9aa7a9161/`,
    },
    // {
    //     id : 6,
    //     imgUrl : `/images/team-member/Samuel Marks.png`,
    //     imgAlt : `Samuel Marks`,
    //     name : `Samuel Marks`,
    //     designation : `Development`,
    //     linkedInImg : `/images/team-member/linkedin.png`,
    //     linkedInAlt : `linkedin Samuel`,
    //     linkedInUrl : `https://www.linkedin.com/in/samuelmarks/`,
    // },
    {
        id : 7,
        imgUrl : `/images/team-member/QuanNguyen.png.pagespeed.ic.VSWJTsdUpY.png`,
        imgAlt : `Quan Nguyen`,
        name : `Quan Nguyen`,
        designation : `Development`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Quan`,
        linkedInUrl : `https://www.linkedin.com/in/quannguyenh/`,
    },
    // {
    //     id : 8,
    //     imgUrl : `/images/team-member/Maxim Zakharov.png`,
    //     imgAlt : `Maxim Zakharov`,
    //     name : `Maxim Zakharov`,
    //     designation : `Development`,
    //     linkedInImg : `/images/team-member/linkedin.png`,
    //     linkedInAlt : `linkedin Maxim`,
    //     linkedInUrl : `https://www.linkedin.com/in/dpmaxime/`,
    // },
    {
        id :  9,
        imgUrl : `/images/team-member/AndreCronjepng.pagespeed.ic.E-xJP1cNRJ.png`,
        imgAlt : `Andre Cronje`,
        name : `Andre Cronje`,
        designation : `Technical Advisor`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Andre`,
        linkedInUrl : `https://www.linkedin.com/in/andre-cronje/`,
    },
    {
        id :  10,
        imgUrl : `/images/team-member/Alex_Kampa.png.pagespeed.ic.o0gt0gRC6m.png`,
        imgAlt : `Alex Kampa`,
        name : `Alex Kampa`,
        designation : `Technical Advisor`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Alex`,
        linkedInUrl : `https://www.linkedin.com/in/aleksander-alex-kampa-97436571/`,
    },
    // {
    //     id :  11,
    //     imgUrl : `/images/team-member/Agustine-min.png`,
    //     imgAlt : `Augustine Chiappe`,
    //     name : `Augustine Chiappe`,
    //     designation : `Development`,
    //     linkedInImg : `/images/team-member/linkedin.png`,
    //     linkedInAlt : `linkedin Augustine`,
    //     linkedInUrl : `https://www.linkedin.com/in/agust%C3%ADn-chiappe-berrini-21369131/`,
    // },
    {
        id :  12,
        imgUrl : `/images/team-member/Maxim Prishchepo.png`,
        imgAlt : `Maxim Prishchepo`,
        name : `Maxim Prishchepo`,
        designation : `Developer`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Maxim`,
        linkedInUrl : `https://www.linkedin.com/in/mprishchepo/`,
    },
    {
        id :  13,
        imgUrl : `/images/team-member/Alexandr Guzev.png`,
        imgAlt : `Alexandr Guzev`,
        name : `Alexander Guzev`,
        designation : `Developer`,
        linkedInImg : ``,
        linkedInAlt : ``,
        linkedInUrl : ``,
    },
    {
        id :  14,
        imgUrl : `/images/team-member/Chernyshov Yury.png`,
        imgAlt : `Yury Chernyshov`,
        name : `Yury Chernyshov`,
        designation : `Developer`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Yury`,
        linkedInUrl : `https://www.linkedin.com/in/yury-chernyshov/`,
    },
    {
        id :  15,
        imgUrl : `/images/team-member/Anatoly Sokolnikov.png`,
        imgAlt : `Anatoly Sokolnikov`,
        name : `Anatoly Sokolnikov`,
        designation : `Developer`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Anatoly`,
        linkedInUrl : `https://www.linkedin.com/in/anatoliy-sokolnikov/`,
    },
    {
        id :  16,
        imgUrl : `/images/team-member/Egor Lysenko.png`,
        imgAlt : `Egor Lysenko`,
        name : `Egor Lysenko`,
        designation : `Developer`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Egor`,
        linkedInUrl : `https://www.linkedin.com/in/egor-lysenko-377186115/`,
    },
    {
        id :  17,
        imgUrl : `/images/team-member/Gleb Selyukov.png`,
        imgAlt : `Gleb Selyukov`,
        name : `Gleb Selyukov`,
        designation : `Developer`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Gleb`,
        linkedInUrl : `https://www.linkedin.com/in/prospik/`,
    },
    {
        id :  18,
        imgUrl : `/images/team-member/Oleg Kislisin.png`,
        imgAlt : `Oleg Kislisin`,
        name : `Oleg Kislisin`,
        designation : `Developer`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Oleg`,
        linkedInUrl : `https://www.linkedin.com/in/oleg-kislitsin-466b38ba/`,
    },
    {
        id :  19,
        imgUrl : `/images/team-member/Kevin.png`,
        imgAlt : `Kevin Kim`,
        name : `Kevin Kim`,
        designation : `Head of Korea`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Kevin`,
        linkedInUrl : `https://www.linkedin.com/in/jhoonkim88/`,
    },

    {
        id :  20,
        imgUrl : `/images/team-member/Brian.png`,
        imgAlt : `Brian Yun`,
        name : `Brian Yun`,
        designation : `Korean Business Director`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Brian`,
        linkedInUrl : `https://www.linkedin.com/in/brian-yun-4b0004119/`,
    },
    {
        id :  21,
        imgUrl : `/images/team-member/GM.png`,
        imgAlt : `GM Chung`,
        name : `GM Chung`,
        designation : `Community Director `,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin GM Chung`,
        linkedInUrl : `https://www.linkedin.com/in/gmchung/`,
    },
    // {
    //     id :  22,
    //     imgUrl : `/images/team-member/CJ.png`,
    //     imgAlt : `CJ Guan`,
    //     name : `CJ Guan`,
    //     designation : `Community Manager `,
    //     linkedInImg : `/images/team-member/linkedin.png`,
    //     linkedInAlt : `linkedin CJ Guan`,
    //     linkedInUrl : `http://linkedin.com/in/cj-g-0a130a23`,
    // },
    {
        id :  22,
        imgUrl : `/images/team-member/James.png`,
        imgAlt : `James Zain`,
        name : `James Zain`,
        designation : `Community Manager`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin James Zain`,
        linkedInUrl : `https://www.linkedin.com/in/james-zain-795a99138/`,
    },
    
    { 
        id :  23,
        imgUrl : `/images/team-member/ConnorHughe.gif`,
        imgAlt : `Connor Hughes`,
        name : `Connor Hughes`,
        designation : `Community Manager`,
        linkedInImg : `/images/team-member/linkedin.png`,
        linkedInAlt : `linkedin Connor Hughes`,
        linkedInUrl : `https://www.linkedin.com/in/connorahughes/`,
    },
    // {
    //     id :  24,
    //     imgUrl : `/images/team-member/Thomas.png`,
    //     imgAlt : `Thomas Lin`,
    //     name : `Thomas Lin`,
    //     designation : `Community Manager`,
    //     linkedInImg : `/images/team-member/linkedin.png`,
    //     linkedInAlt : `linkedin Thomas Lin`,
    //     linkedInUrl : `https://www.linkedin.com/in/thomas-lin1985/`,
    // },
]

export const teamData = [
    {
        heading:`Meet the team`,
        discription:`Our team members collectively have years of research and development experience in networking, distributed systems, middleware research, and running technology companies.`,
    }
]